name: 'Linter code'

on:
  pull_request:
    branches:
    - main

jobs:
  install-node-modules-and-lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Linter code
        run: npm run lint
      - name: Linter styles
        run: npm run lint:style
  unit-testing-components:
    runs-on: ubuntu-18.04
    steps:
      - name: testing atoms components
        run: npm run test:unit

